name: Branch Name Check

on:
  create:
    branches:
      - '*'

jobs:
  branch-name-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check branch name
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "Branch name is $branch_name"
          if [[ ! "$branch_name" =~ ^(feature|bugfix|hotfix)/.+$ ]]; then
            echo "Branch name does not follow the required format."
            echo "Please use one of the following prefixes: 'feature/', 'bugfix/', or 'hotfix/'."
            exit 1
          fi
