name: Branch Naming Convention

on:
  push:
    branches:
      - '*'

jobs:
  enforce-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          # Add your custom branch name validation logic here
          # For example, to enforce a specific format:
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          if [[ ! "$branch_name" =~ ^feature/.* ]]; then
            echo "Branch name must start with 'feature/'"
            exit 1
          fi
          # Prevent branch creation if the name doesn't match
          if [[ "$GITHUB_EVENT_NAME" == "create" ]]; then
            echo "Branch creation not allowed."
            exit 1
          fi
